// Generated by typings
// Source: https://raw.githubusercontent.com/dsherret/server-bridge-base-client/404f3f7a3993fae3a8da0518ff738e2f096a91a0/server-bridge-base-client.d.ts
declare module '~server-bridge-base-client/server-bridge-base-client' {
export abstract class BaseClient {
    protected baseUrl: string;
    constructor(baseUrl: string);
    protected abstract get<ReturnType>(url: string, args?: Object): Promise<ReturnType>;
    protected abstract post<ReturnType>(url: string, sendObj: any, args?: Object): Promise<ReturnType>;
}
}
declare module 'server-bridge-base-client/server-bridge-base-client' {
export * from '~server-bridge-base-client/server-bridge-base-client';
}
declare module 'server-bridge-base-client' {
export * from '~server-bridge-base-client/server-bridge-base-client';
}
